name: blanket # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
adopt-info: blanket
parts:
  blanket:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/rafaelmardojai/blanket.git
    source-tag: '0.6.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/blanket/current/usr
    parse-info: [usr/share/metainfo/com.rafaelmardojai.Blanket.metainfo.xml] 
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/blanket.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/blanket/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
      sed -e '1c#!/usr/bin/env python3' -i $CRAFT_PART_INSTALL/snap/blanket/current/usr/bin/blanket
    organize:
      snap/blanket/current: .
    prime:
      - -snap/blanket
  deps:
    plugin: nil
    stage-packages:
      - libgstreamer-plugins-bad1.0-0
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-bad-1.0 
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - blanket
      - deps
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gtk-common-themes
      - gnome-42-2204
      - core22
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done


slots:
  blanket-mpris:
    interface: mpris
    name: Blanket
  blanket:
    interface: dbus
    bus: session
    name: com.rafaelmardojai.Blanket

apps:
  blanket:
    command: usr/bin/blanket
    extensions: [gnome]
    common-id: com.rafaelmardojai.Blanket
    plugs:
      - audio-playback
